#ddev-generated

http:
  routers:
    
    
    git-summary-web-80-http:
      
      rule: HostRegexp(`git-summary.ddev.site`)
      
      service: "git-summary-web-80-http"
      tls: false
      entrypoints:
        - http-80
    
    
    git-summary-web-8025-http:
      
      rule: HostRegexp(`git-summary.ddev.site`)
      
      service: "git-summary-web-8025-http"
      tls: false
      entrypoints:
        - http-8025
    
    
    
    
    
    
    git-summary-web-80-https:
      
      rule: HostRegexp(`git-summary.ddev.site`)
      
      service: "git-summary-web-80-https"
      
      tls: true
      
      entrypoints:
        - http-443
    
    
    git-summary-web-8025-https:
      
      rule: HostRegexp(`git-summary.ddev.site`)
      
      service: "git-summary-web-8025-https"
      
      tls: true
      
      entrypoints:
        - http-8026
    
    

  services:
    
    git-summary-web-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-git-summary-web:80
    
    git-summary-web-8025-http:
      loadbalancer:
        servers:
          - url: http://ddev-git-summary-web:8025
    
    git-summary-web-80-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-git-summary-web:80
    
    git-summary-web-8025-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-git-summary-web:8025
    


tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/git-summary.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/git-summary.key

